services:

  # REST API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boilerplate_api
    restart: unless-stopped
    command: /app/api
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./videos:/app/videos
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - boilerplate_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # gRPC Service
  grpc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boilerplate_grpc
    restart: unless-stopped
    command: /app/grpc
    env_file:
      - .env
    ports:
      - "${GRPC_PORT:-50051}:50051"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - boilerplate_network

networks:
  boilerplate_network:
    driver: bridge